Search.appendIndex(
    [
                {
            "fqsen": "\\sfv_get_post_video_source\u0028\u0029",
            "name": "sfv_get_post_video_source",
            "summary": "Retrieves\u0020the\u0020post\u0020video\u0020source.",
            "url": "namespaces/default.html#function_sfv_get_post_video_source"
        },                {
            "fqsen": "\\sfv_has_post_video\u0028\u0029",
            "name": "sfv_has_post_video",
            "summary": "Determines\u0020whether\u0020a\u0020post\u0020has\u0020a\u0020video\u0020attached.",
            "url": "namespaces/default.html#function_sfv_has_post_video"
        },                {
            "fqsen": "\\sfv_get_post_video_id\u0028\u0029",
            "name": "sfv_get_post_video_id",
            "summary": "Retrieves\u0020the\u0020post\u0020video\u0020ID.",
            "url": "namespaces/default.html#function_sfv_get_post_video_id"
        },                {
            "fqsen": "\\sfv_the_post_video\u0028\u0029",
            "name": "sfv_the_post_video",
            "summary": "Displays\u0020the\u0020post\u0020video.",
            "url": "namespaces/default.html#function_sfv_the_post_video"
        },                {
            "fqsen": "\\sfv_get_the_post_video\u0028\u0029",
            "name": "sfv_get_the_post_video",
            "summary": "Retrieves\u0020the\u0020post\u0020video.",
            "url": "namespaces/default.html#function_sfv_get_the_post_video"
        },                {
            "fqsen": "\\sfv_the_post_video_url\u0028\u0029",
            "name": "sfv_the_post_video_url",
            "summary": "Displays\u0020the\u0020post\u0020video\u0020URL.",
            "url": "namespaces/default.html#function_sfv_the_post_video_url"
        },                {
            "fqsen": "\\sfv_get_the_post_video_url\u0028\u0029",
            "name": "sfv_get_the_post_video_url",
            "summary": "Returns\u0020the\u0020post\u0020video\u0020URL.",
            "url": "namespaces/default.html#function_sfv_get_the_post_video_url"
        },                {
            "fqsen": "\\sfv_the_post_video_caption\u0028\u0029",
            "name": "sfv_the_post_video_caption",
            "summary": "Displays\u0020the\u0020post\u0020video\u0020caption.",
            "url": "namespaces/default.html#function_sfv_the_post_video_caption"
        },                {
            "fqsen": "\\sfv_get_the_post_video_caption\u0028\u0029",
            "name": "sfv_get_the_post_video_caption",
            "summary": "Returns\u0020the\u0020post\u0020video\u0020caption.",
            "url": "namespaces/default.html#function_sfv_get_the_post_video_caption"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
